### ISSUE TITLE
sandbox: self-delegate 70% of the tokens

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/devopstools#11]
We plan to use `Protocol Upgrade` to upgrade the version on the `sandbox` network. This requires a validator's vote. We will be in control of only one validator in that network, all the other validators will be run by externals, not controlled by us parties. We can't expect them to vote, so we need a clever solution.

Thankfully the vote is weighted with the validator's stake, i.e. the validator's vote power is proportional to the amount of token staked to it.

The idea is to stake 70% of the total amount of tokens to our validator in order to get the votes through.

https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1666088736848069?thread_ts=1666006161.214869&cid=C9E6XA8GK

**Comment by gordsport** [comment]
Blocked/Parked: https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1666181081378149?thread_ts=1666006161.214869&cid=C9E6XA8GK

**Comment by JonRay15** [comment]
This is now not the way ...

we're doing this https://github.com/vegaprotocol/devops-infra/issues/1593
