### ISSUE TITLE
Add support for the GITHUB_TOKEN

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/devopstools#22]
We should allow to use the GITHUB_TOKEN env variable next to the secret.txt file. This environment variable is well known and it is used by all of the github apps. 

https://devopsjournal.io/blog/2022/01/03/GitHub-Tokens#:~:text=2.-,The%20GITHUB_TOKEN%20environment%20variable,workflow%20it%20was%20created%20for.

**Comment by fkondej** [comment]
nice to have, but low priority
